global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'chat-backend'
    static_configs:
      - targets: ['app-deployment-backend-1:5001']
