name: ChatApp Full CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend ./app-deployment/backend

      - name: Build frontend image
        run: docker build -t frontend ./app-deployment/frontend

      - name: Run backend container test
        run: docker run -d -p 5000:5000 --name backend-test backend

      - name: Run frontend container test
        run: docker run -d -p 8080:80 --name frontend-test frontend

      - name: Verify running containers
        run: docker ps

      - name: Deployment successful
        run: echo "Application built, tested and deployed"
